# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterpullsecrets.ops.alexellis.io
spec:
  group: ops.alexellis.io
  names:
    kind: ClusterPullSecret
    listKind: ClusterPullSecretList
    plural: clusterpullsecrets
    singular: clusterpullsecretpullsecret
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.secretRef.name
          name: SecretName
          type: string
        - jsonPath: .spec.secretRef.namespace
          name: SecretNamespace
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: ClusterPullSecret is the Schema for the clusterpullsecrets API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
               of an object. Servers should convert recognized schemas to the latest
               internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
               object represents. Servers may infer this from the endpoint the client
               submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: ClusterPullSecretSpec defines the desired state of ClusterPullSecret
              properties:
                secretRef:
                  description: ObjectMeta contains enough information to locate the
                    referenced Kubernetes resource object in any namespace.
                  properties:
                    name:
                      description: Name of the referent.
                      type: string
                    namespace:
                      description: Namespace of the referent, when not specified it
                        acts as LocalObjectReference.
                      type: string
                  required:
                    - name
                  type: object
              type: object
            status:
              description: ClusterPullSecretStatus defines the observed state of ClusterPullSecret
              type: object
          type: object
      served: true
      storage: true
      subresources: { }
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v1beta1"]
      clientConfig:
        # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
        # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
        caBundle: Cg==
        service:
          namespace: system
          name: webhook-service
          path: /convert
